# Generated by Django 4.0.5 on 2022-07-04 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle_hash', models.CharField(max_length=128, verbose_name='标题:')),
                ('plaintext_hash', models.TextField(verbose_name='明文哈希值:')),
                ('chipertext_hash', models.TextField(verbose_name='密文哈希值:')),
                ('encode_ways', models.CharField(max_length=10, verbose_name='加密方式:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_system.userinfo')),
            ],
        ),
    ]
