# Generated by Django 4.0.5 on 2022-07-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='private_key',
            field=models.CharField(default='', max_length=64, verbose_name='公钥'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='public_key',
            field=models.CharField(default='', max_length=128, verbose_name='私钥'),
        ),
    ]
